import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";



export const metadata: Metadata = {
  title: "eBantuan JKM 2.0 Dev",
  description: "Generated by Next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ms">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
